unit-test:
  container_name: CashrewardsOffers-unit-test
  image: mcr.microsoft.com/dotnet/sdk:6.0
  command: sh /app/run-unit-test.sh "${CURRENT_UID}"
  working_dir: /app
  volumes:
  - ./:/app

integration-test:
  container_name: CashrewardsOffers-integration-test
  image: mcr.microsoft.com/dotnet/sdk:6.0
  command: sh /app/run-integration-test.sh "${CURRENT_UID}"
  working_dir: /app
  volumes:
  - ./:/app