// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CashrewardsOffers.Application.AcceptanceTests.Features.Anz
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("AnzFeaturedSequence")]
    public partial class AnzFeaturedSequenceFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "AnzFeaturedSequence.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-AU"), "Features/Anz", "AnzFeaturedSequence", null, ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Featured offer items should be ordered by rank then first ending")]
        public void FeaturedOfferItemsShouldBeOrderedByRankThenFirstEnding()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Featured offer items should be ordered by rank then first ending", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 3
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table100 = new TechTalk.SpecFlow.Table(new string[] {
                            "Merchant.Id",
                            "EndDateTime",
                            "IsFeatured",
                            "OfferId",
                            "Ranking"});
                table100.AddRow(new string[] {
                            "100",
                            "637922304380000000",
                            "true",
                            "100",
                            "0"});
                table100.AddRow(new string[] {
                            "101",
                            "637922304380000000",
                            "true",
                            "101",
                            "0"});
                table100.AddRow(new string[] {
                            "102",
                            "637922304380000000",
                            "true",
                            "102",
                            "0"});
                table100.AddRow(new string[] {
                            "103",
                            "637922304380000000",
                            "true",
                            "103",
                            "1"});
                table100.AddRow(new string[] {
                            "104",
                            "637922304380000000",
                            "true",
                            "104",
                            "0"});
                table100.AddRow(new string[] {
                            "105",
                            "637922304380000000",
                            "true",
                            "105",
                            "999"});
#line 4
 testRunner.Given("offer data change event", ((string)(null)), table100, "Given ");
#line hidden
#line 12
 testRunner.When("I send an ANZ query", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table101 = new TechTalk.SpecFlow.Table(new string[] {
                            "ItemId",
                            "Offer.IsFeatured",
                            "Offer.FeaturedRanking"});
                table101.AddRow(new string[] {
                            "100-100",
                            "true",
                            "3"});
                table101.AddRow(new string[] {
                            "101-101",
                            "true",
                            "4"});
                table101.AddRow(new string[] {
                            "102-102",
                            "true",
                            "5"});
                table101.AddRow(new string[] {
                            "103-103",
                            "true",
                            "2"});
                table101.AddRow(new string[] {
                            "104-104",
                            "true",
                            "6"});
                table101.AddRow(new string[] {
                            "105-105",
                            "true",
                            "1"});
#line 13
 testRunner.Then("I should receive ANZ items", ((string)(null)), table101, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Only Featured offers should update when events come through")]
        public void OnlyFeaturedOffersShouldUpdateWhenEventsComeThrough()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Only Featured offers should update when events come through", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 22
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table102 = new TechTalk.SpecFlow.Table(new string[] {
                            "Merchant.Id",
                            "EndDateTime",
                            "IsFeatured",
                            "OfferId",
                            "Ranking"});
                table102.AddRow(new string[] {
                            "100",
                            "637922304380000000",
                            "true",
                            "100",
                            "0"});
                table102.AddRow(new string[] {
                            "101",
                            "637922304380000000",
                            "true",
                            "101",
                            "0"});
                table102.AddRow(new string[] {
                            "102",
                            "637922304380000000",
                            "true",
                            "102",
                            "0"});
                table102.AddRow(new string[] {
                            "103",
                            "637922304380000000",
                            "true",
                            "103",
                            "1"});
                table102.AddRow(new string[] {
                            "104",
                            "637922304380000000",
                            "true",
                            "104",
                            "0"});
                table102.AddRow(new string[] {
                            "105",
                            "637922304380000000",
                            "true",
                            "105",
                            "999"});
#line 23
 testRunner.Given("offer data change event", ((string)(null)), table102, "Given ");
#line hidden
#line 31
 testRunner.When("I send an ANZ query", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table103 = new TechTalk.SpecFlow.Table(new string[] {
                            "ItemId",
                            "Offer.IsFeatured",
                            "Offer.FeaturedRanking"});
                table103.AddRow(new string[] {
                            "100-100",
                            "true",
                            "3"});
                table103.AddRow(new string[] {
                            "101-101",
                            "true",
                            "4"});
                table103.AddRow(new string[] {
                            "102-102",
                            "true",
                            "5"});
                table103.AddRow(new string[] {
                            "103-103",
                            "true",
                            "2"});
                table103.AddRow(new string[] {
                            "104-104",
                            "true",
                            "6"});
                table103.AddRow(new string[] {
                            "105-105",
                            "true",
                            "1"});
#line 32
 testRunner.Then("I should receive ANZ items", ((string)(null)), table103, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table104 = new TechTalk.SpecFlow.Table(new string[] {
                            "Merchant.Id",
                            "EndDateTime",
                            "IsFeatured",
                            "OfferId",
                            "Ranking"});
                table104.AddRow(new string[] {
                            "106",
                            "637922304380000000",
                            "true",
                            "106",
                            "1"});
#line 40
 testRunner.Given("offer data change event", ((string)(null)), table104, "Given ");
#line hidden
#line 43
 testRunner.When("I send an ANZ query", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table105 = new TechTalk.SpecFlow.Table(new string[] {
                            "ItemId",
                            "Offer.IsFeatured",
                            "Offer.FeaturedRanking"});
                table105.AddRow(new string[] {
                            "100-100",
                            "true",
                            "4"});
                table105.AddRow(new string[] {
                            "101-101",
                            "true",
                            "5"});
                table105.AddRow(new string[] {
                            "102-102",
                            "true",
                            "6"});
                table105.AddRow(new string[] {
                            "103-103",
                            "true",
                            "2"});
                table105.AddRow(new string[] {
                            "104-104",
                            "true",
                            "7"});
                table105.AddRow(new string[] {
                            "105-105",
                            "true",
                            "1"});
                table105.AddRow(new string[] {
                            "106-106",
                            "true",
                            "3"});
#line 44
 testRunner.Then("I should receive ANZ items", ((string)(null)), table105, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table106 = new TechTalk.SpecFlow.Table(new string[] {
                            "Merchant.Id",
                            "EndDateTime",
                            "IsFeatured",
                            "OfferId",
                            "Ranking"});
                table106.AddRow(new string[] {
                            "103",
                            "637922304380000000",
                            "false",
                            "103",
                            "1"});
#line 53
 testRunner.Given("offer data change event", ((string)(null)), table106, "Given ");
#line hidden
#line 56
 testRunner.When("I send an ANZ query", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table107 = new TechTalk.SpecFlow.Table(new string[] {
                            "ItemId",
                            "Offer.IsFeatured",
                            "Offer.FeaturedRanking"});
                table107.AddRow(new string[] {
                            "100-100",
                            "true",
                            "3"});
                table107.AddRow(new string[] {
                            "101-101",
                            "true",
                            "4"});
                table107.AddRow(new string[] {
                            "102-102",
                            "true",
                            "5"});
                table107.AddRow(new string[] {
                            "104-104",
                            "true",
                            "6"});
                table107.AddRow(new string[] {
                            "105-105",
                            "true",
                            "1"});
                table107.AddRow(new string[] {
                            "106-106",
                            "true",
                            "2"});
#line 57
 testRunner.Then("I should receive ANZ items", ((string)(null)), table107, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table108 = new TechTalk.SpecFlow.Table(new string[] {
                            "Merchant.Id"});
                table108.AddRow(new string[] {
                            "102"});
#line 65
 testRunner.Given("offer data change event", ((string)(null)), table108, "Given ");
#line hidden
#line 68
 testRunner.When("I send an ANZ query", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table109 = new TechTalk.SpecFlow.Table(new string[] {
                            "ItemId",
                            "Offer.IsFeatured",
                            "Offer.FeaturedRanking"});
                table109.AddRow(new string[] {
                            "100-100",
                            "true",
                            "3"});
                table109.AddRow(new string[] {
                            "101-101",
                            "true",
                            "4"});
                table109.AddRow(new string[] {
                            "102-102",
                            "true",
                            "5"});
                table109.AddRow(new string[] {
                            "104-104",
                            "true",
                            "6"});
                table109.AddRow(new string[] {
                            "105-105",
                            "true",
                            "1"});
                table109.AddRow(new string[] {
                            "106-106",
                            "true",
                            "2"});
#line 69
 testRunner.Then("I should receive ANZ items", ((string)(null)), table109, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table110 = new TechTalk.SpecFlow.Table(new string[] {
                            "Merchant.Id",
                            "EndDateTime"});
                table110.AddRow(new string[] {
                            "102",
                            "627922304380000000"});
#line 77
 testRunner.Given("offer data change event", ((string)(null)), table110, "Given ");
#line hidden
#line 80
 testRunner.When("I send an ANZ query", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table111 = new TechTalk.SpecFlow.Table(new string[] {
                            "ItemId",
                            "Offer.IsFeatured",
                            "Offer.FeaturedRanking"});
                table111.AddRow(new string[] {
                            "100-100",
                            "true",
                            "4"});
                table111.AddRow(new string[] {
                            "101-101",
                            "true",
                            "5"});
                table111.AddRow(new string[] {
                            "102-102",
                            "true",
                            "3"});
                table111.AddRow(new string[] {
                            "104-104",
                            "true",
                            "6"});
                table111.AddRow(new string[] {
                            "105-105",
                            "true",
                            "1"});
                table111.AddRow(new string[] {
                            "106-106",
                            "true",
                            "2"});
#line 81
 testRunner.Then("I should receive ANZ items", ((string)(null)), table111, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table112 = new TechTalk.SpecFlow.Table(new string[] {
                            "OfferId",
                            "Merchant.Id"});
                table112.AddRow(new string[] {
                            "106",
                            "106"});
#line 89
 testRunner.Given("offer delete event", ((string)(null)), table112, "Given ");
#line hidden
#line 92
 testRunner.When("I send an ANZ query", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table113 = new TechTalk.SpecFlow.Table(new string[] {
                            "ItemId",
                            "Offer.IsFeatured",
                            "Offer.FeaturedRanking"});
                table113.AddRow(new string[] {
                            "100-100",
                            "true",
                            "3"});
                table113.AddRow(new string[] {
                            "101-101",
                            "true",
                            "4"});
                table113.AddRow(new string[] {
                            "102-102",
                            "true",
                            "2"});
                table113.AddRow(new string[] {
                            "104-104",
                            "true",
                            "5"});
                table113.AddRow(new string[] {
                            "105-105",
                            "true",
                            "1"});
#line 93
 testRunner.Then("I should receive ANZ items", ((string)(null)), table113, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table114 = new TechTalk.SpecFlow.Table(new string[] {
                            "Merchant.Id",
                            "EndDateTime",
                            "IsFeatured",
                            "OfferId",
                            "Ranking"});
                table114.AddRow(new string[] {
                            "106",
                            "637922304380000000",
                            "true",
                            "106",
                            "1"});
#line 100
 testRunner.Given("offer data change event", ((string)(null)), table114, "Given ");
#line hidden
#line 103
 testRunner.When("I send an ANZ query", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table115 = new TechTalk.SpecFlow.Table(new string[] {
                            "ItemId",
                            "Offer.IsFeatured",
                            "Offer.FeaturedRanking"});
                table115.AddRow(new string[] {
                            "100-100",
                            "true",
                            "4"});
                table115.AddRow(new string[] {
                            "101-101",
                            "true",
                            "5"});
                table115.AddRow(new string[] {
                            "102-102",
                            "true",
                            "3"});
                table115.AddRow(new string[] {
                            "104-104",
                            "true",
                            "6"});
                table115.AddRow(new string[] {
                            "105-105",
                            "true",
                            "1"});
                table115.AddRow(new string[] {
                            "106-106",
                            "true",
                            "2"});
#line 104
 testRunner.Then("I should receive ANZ items", ((string)(null)), table115, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
